baseURL = 'https://github.com/haydenk/hugo-hondo/'
languageCode = 'en-US'
title = 'Hondo Theme'
theme = 'hugo-hondo'
disableKinds = [ "taxonomy" ]
ignoreErrors = [ "error-disable-taxonomy" ]

[module]
  [module.hugoVersion]
    extended = false
    min      = "0.112.0"

[params]
  description = "Hondo Theme"
  keywords = []

  mainCss = '/css/main.css'
  mainJs = '/js/main.js'
  [[params.baseStyles]]
    src = 'css/variables.css'
  [[params.baseStyles]]
    src = 'css/main.css'
  [[params.baseStyles]]
    src = 'css/syntax.css'

[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[menus.main]]
  name = "Today"
  pageRef = "/today"
  weight = 12

[[menus.main]]
  name = 'About'
  pageRef = '/about'
  weight = 20

[[menus.main]]
  name = 'Github'
  url = 'https://github.com/haydenk/hugo-hondo'
  weight = 99
  [menus.main.params]
    target = '_blank'
    rel = 'external'

[permalinks]
  [permalinks.page]
    posts = '/post/:year/:month/:day/:slug/'
    today = '/today/:year-:month-:day/'
  [permalinks.section]
    posts = '/post/'
    today = '/today/'

[outputFormats]
  [outputFormats.rss]
    mediaType = "application/rss+xml"
    baseName = "feed"
  [outputFormats.json]
    mediaType = "application/json"
    baseName = "feed"
    isPlainText = true

[outputs]
  home = ['html','json','rss']
  page = ['html']
  section = ['html']
  taxonomy = ['html']
  term = ['html']

[pagination]
  pagerSize = 10

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
